[package]
name = "server"
version = "0.1.0"
authors = ["m-mueller678"]

[dependencies]
common = {path="../common",features=["protocol"]}
mio = "0.6.4"
time = "0.1.36"
env_logger = "0.4.0"
log = "0.3.6"